### PR TITLE
feat: add markdown content route config

### PR DESCRIPTION
**Pull request by noxasch**
- update index.spec.js

- reduce markdown input to bare minimum

address #61

### CODE REVIEW

**Comment by noxasch** [comment]
As i have been testing while using, if we put the markdown files outside of the src folder, rollup will not watch the changes. Do we have any interface to include those folder into chokidar config inside the elderjs rollupPlugin ?

**Comment by nickreese** [comment]
@noxasch Currently no interface on `chokidar` but it does watch the `./src/`.

I'm open to sending an array of files to the watcher once we get a stable interface. 

On the `next` branch we have a pretty stable `esbuild` setup but on release it will still be tagged as experimental as we're evaluating `vite` to see if we can get an easy with with HMR with the help of a few people in the Svelte community.

**Comment by nickreese** [comment]
@noxasch Looks great to me. Elegant and clean, I think an example of how to use it in the `readme.md` would be helpful.

Great job as always.

**Comment by noxasch** [comment]
@nickreese done with the docs.

> @noxasch Currently no interface on `chokidar` but it does watch the `./src/`.
> 
> I'm open to sending an array of files to the watcher once we get a stable interface.
> 
> On the `next` branch we have a pretty stable `esbuild` setup but on release it will still be tagged as experimental as we're evaluating `vite` to see if we can get an easy with with HMR with the help of a few people in the Svelte community.

That'll be great. Btw should I make a new PR for the plugin-images which address a bug that happen when we set image `src` in the config to be the same path as `contents` in the plugin-markdown, the plugin will throw `elderjs-plugin-images: no manifest found at <PATH>`. This will also fix #67 at the same time.

**Comment by nickreese** [comment]
@noxasch That would be awesome. I'll get this one merged and shipped. Looks great. You're a rockstar.

**Pull request merged**
