### PR TITLE
markdown - Fix syntax highlighting

### PR DESCRIPTION
**Pull request by fli**
- Makes the plugin init async
- Inserts generated HTML as html node in the markdown syntax tree
- Bumps package versions and removes unused packages

### CODE REVIEW

**Comment by nickreese** [comment]
@fli reviewing the PR not sure what the code that was removed was doing. Can you help me make sense of it? Cc: @sw-yx would love you eyes on this if you have a moment.

**Comment by sw-yx** [comment]
im ok with it, that code was copied over from https://github.com/rsclarke/rehype-shiki/blob/master/index.js which is unmaintained. if this works it works

**Comment by fli** [comment]
Problems:
1. The syntax tree input into the transformer is a [markdown syntax tree](https://github.com/syntax-tree/mdast) not an [HTML syntax tree](https://github.com/syntax-tree/hast), so checking for `<pre><code>{code here}</code></pre>` (on L38) won't ever trigger.
2. Most of the extra code is manually generating the syntax highlighting by adding spans around the elements then styling them with the `style` attribute. But shiki has a `codeToHtml` function that does that for you.
3. Since the syntax tree is a markdown syntax tree, and markdown can render an html node, and shiki can give us an html node, we just replace the `code` element with an `html` element with the output of `codeToHtml`

**Comment by nickreese** [comment]
@fli thanks for outlining this. I still had my test branch for this functionality of the plugin and when I tested it again before merging, the output didn’t appear to change much if at all, so I was surprised. Makes sense now. 👍 Thanks for helping make this great.

**Pull request merged**
