### PR TITLE
Adds an option to use a fn to format slug; adds debug

### PR DESCRIPTION
**Pull request by albertlincoln**
Hi, cool project, nice ideas. Let me know if this is something you think is helpful.

### CODE REVIEW

**Comment by nickreese** [comment]
@albertlincoln Thanks for the PR. Honestly unfamiliar with debug. 👀  😅 

I like the idea. To make the idea easier to grok, do you think passing in just the file name would be enough? EG. `path.parse(file)` as the function param? That gives the user:
```
{ 
root: '/',
dir: '/home/user/dir',
base: 'file.txt',
ext: '.txt',
name: 'file'
}
```
Which is effectively what you're achieving, right?

**Comment by nickreese** [comment]
@albertlincoln thinking more on this. I really think a `path.parse` object, the slug frontmatter should be passed into the function. Further if the function exists it should override the other options. (Basically first in the if/else tree). 

Check this ticket for a request of where this would be useful: https://github.com/Elderjs/elderjs/issues/82

**Comment by albertlincoln** [comment]
I'll remove debug for this PR. For what its worth, its awesome. https://www.npmjs.com/package/debug 85M downloads weekly. A little dated but conceptually rock-solid. Works in a terminal console as well as the browser. :-)

**Comment by nickreese** [comment]
@albertlincoln Thanks for exposing me to it. Also, the more I think about this PR, the more I see how required it is. Thanks for the help on it.  👍

**Comment by albertlincoln** [comment]
Anyway - about the slug:

* Agree it should override the other options, except I'm on the fence if the file has a slug defined in the frontmatter.
* Not sure what you mean by this:

> I really think a path.parse object, the slug frontmatter should be passed into the function.

* If you mean that the result of path.parse(file) *and* the _page frontmatter_ should get passed into the function, I'm fine with that. It hands off the logic of what to do when the frontmatter has a slug. However, I think the file or parsed file needs to the be relative path from the blog route.

Just saw your note. Glad to help.

**Comment by nickreese** [comment]
@albertlincoln maybe we can have our cake and eat it too. If the fn doesn’t return a string or is undefined it defaults to the other options?

As for params: 

Why not just pass in the full path and any slug from frontmatter if available? 

We can also add the route root if you think there is a use case that can’t be solved without it. 

(My general rule is any fn with more than 2 params should use an object and destructuring.)

Also: https://nodejs.org/docs/latest-v12.x/api/path.html#path_path_relative_from_to so to help with Windows paths if you’re really of the opinion a rel path is important.

**Comment by albertlincoln** [comment]
@nickreese - I had thought about adding the slug to the frontmatter via a remark plugin and still like the idea. Is there a reason the elderimage plugin isn't a remark plugin? (I'm just getting familiar with remark!) It would require adding the `to-vfile` plugin so that the readSync would result in:

```
VFile {
  data: {},
  messages: [],
  history: [ './src/routes/blog/getting-started.md' ],
  cwd: '/home/all/src/Elderjs/elderjs-app',
  contents: <Buffer 2d 2d 2d 0a 74 69 74 6c 65 3a 20 27 47 65 74 74 69 6e 67 20 53 74 61 72 74 65 64 20 77 69 74 68 20 45 6c 64 65 72 2e 6a 73 27 0a 65 78 63 65 72 70 74 ... 7813 more bytes>
}
```

The route can be added to the vFile object, or the data prop, and then `plugin-slug` would do its thing. The plugin would modify the `data.frontmattter` property based on the function it was configured with. Let me try that.

> @albertlincoln maybe we can have our cake and eat it too. If the fn doesn’t return a string or is undefined it defaults to the other options?

Definitely! That's what I've got in the PR at the moment.

The reason for including the route is for safety and to support to the client for whatever they want to do. For example, I have all my posts in docunext.com organized by year and month only. Its possible I might have a folder with the same name as the base route being processed by the plugin.

If I have a `src/routes/blog/2020/11/blog/creating-slugs-with-elderjs.md` file, the slug should be: `2010/11/blog/creating-slugs-with-elderjs`. Some clients may prefer including the `blog` prefix, and who knows what else. It still could be split safely but I'm for being adaptable.

**Comment by albertlincoln** [comment]
Got it -- will open a new pr.

**Comment by albertlincoln** [comment]
Back to the original design - think I understand your points better now. Let me know what you think.

**Comment by nickreese** [comment]
@albertlincoln So as far as remark plugins. The main reason for overwriting it is because often plugin order matters. :) Looking at the PR now.

**Comment by nickreese** [comment]
@albertlincoln  Two small things and let's get this bad-boy merged. 

1. In playing with this, I think you're right on the relative path. Lots of hoop jumping to get the part of the path that matters without it. I can see why this would be the easiest for the user. 
1. Let's document the function in the readme.

Do you see any reason a user might want the frontmatter passed in as a function param?

**Comment by nickreese** [comment]
@albertlincoln Lol. I feel soo indecisive on this. Ended up with almost the idential solution to you in the template without looking at it. Whatever you think is best. I think this is merge ready unless you think the rel path is a better solution.

**Comment by albertlincoln** [comment]
> @albertlincoln Two small things and let's get this bad-boy merged.
> 
> 1. In playing with this, I think you're right on the relative path. Lots of hoop jumping to get the part of the path that matters without it. I can see why this would be the easiest for the user.
> 2. Let's document the function in the readme.
> 
> Do you see any reason a user might want the frontmatter passed in as a function param?

@nickreese ! Cool! I vote for relpath. Will update and document.

Regarding the frontmatter, I think its a great idea so will add that in for consideration. Reason being that some people may have a slug defined in there that needs modification, or they may want to use the date from the frontmatter.

**Comment by albertlincoln** [comment]
Let me know if there is anything else!

**Comment by albertlincoln** [comment]
Hi @nickreese  -following up, everything in line or is there something else? I'd like to get this merged so I can use it!

**Comment by nickreese** [comment]
@albertlincoln Thanks! This is great. Pardon the delay had some other pressing issues come up.

**Comment by albertlincoln** [comment]
No worries - glad it worked out.

**Pull request merged**
